name: HACS Validation

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration