name: Hassfest

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@58bff37c8947f690ace498be413a9b78d6f30f93
        with:
          path: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}